name: Release
on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/ga/tag-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-type: patch
